platform :ios, '10.0'

target 'Cinephiles' do
  
  use_frameworks!
  inhibit_all_warnings!

  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'PKHUD'
  pod 'ReachabilitySwift'
  pod 'SDWebImage'

end
